services:
  backend:
    build: ./backend
    container_name: campus-vote-backend
    ports:
      - "8545:8545"

  frontend:
    build: ./frontend
    container_name: campus-vote-frontend
    ports:
      - "3000:3000"
